"""AURA Evidence Requirement Engine.

Analyzes a canonical DecisionModel and derives a deduplicated, policy-enforced
list of EvidenceRequirement entities.

Guarantees:
- Distinguishes EXTERNAL_RESEARCH, INTERNAL_DATA, USER_CLARIFICATION, and DETERMINISTIC_CALCULATION.
- Strictly bounds search queries: only EXTERNAL_RESEARCH may possess suggested_queries.
- Wipes/prevents queries on INTERNAL_DATA, USER_CLARIFICATION, and DETERMINISTIC_CALCULATION.
- Enforces status=PENDING for all newly generated requirements.
- Validates that target_entity_id exists in DecisionModel and matches target_entity_type.
- Prevents generating requirements to verify facts already provided by the user.
- Employs dependency-injected LLMClient without making external network calls in tests.
"""

import time
from typing import Any, Dict, List, Optional, Set
from pydantic import BaseModel, ConfigDict, Field

from app.schemas.decision_model import (
    CriticalityLevel,
    DecisionModel,
    ProvenanceType,
)
from app.schemas.evidence import (
    DecisionEntityType,
    EvidenceKind,
    EvidenceRequirement,
    RequirementStatus,
)
from app.services.llm.client import LLMClient, LLMTimeoutError


# ------------------------------------------------------------------------------
# 1. Candidate Structured Output Models (LLM Interface)
# ------------------------------------------------------------------------------

class CandidateEvidenceRequirement(BaseModel):
    """Raw candidate requirement proposal generated by the language model."""
    model_config = ConfigDict(str_strip_whitespace=True)

    target_entity_id: str = Field(
        ...,
        min_length=1,
        max_length=64,
        description="ID of entity in DecisionModel requiring empirical validation.",
    )
    target_entity_type: DecisionEntityType = Field(
        ...,
        description="Entity taxonomy classification matching DecisionModel collection.",
    )
    kind: EvidenceKind = Field(
        ...,
        description="Inquiry kind: external_research, internal_data, user_clarification, deterministic_calculation.",
    )
    description: str = Field(
        ...,
        min_length=3,
        description="Factual question or hypothesis needing validation.",
    )
    priority: CriticalityLevel = Field(
        default=CriticalityLevel.MEDIUM,
        description="Assessed priority (low, medium, high).",
    )
    suggested_queries: List[str] = Field(
        default_factory=list,
        description="Suggested search query strings (strictly for external_research only).",
    )


class CandidateRequirementsPayload(BaseModel):
    """Container schema for structured candidate requirements output by LLM."""
    model_config = ConfigDict(str_strip_whitespace=True)

    requirements: List[CandidateEvidenceRequirement] = Field(
        default_factory=list,
        description="List of candidate requirements identified.",
    )


# ------------------------------------------------------------------------------
# 2. Prompts & Instructions
# ------------------------------------------------------------------------------

REQUIREMENTS_SYSTEM_PROMPT = """You are AURA's Evidence Requirement Analyst.
Your objective is to analyze a structured DecisionModel and determine what empirical information, data points, or calculations are strictly required to resolve the decision under uncertainty.

For each requirement:
1. Target an explicit existing entity from the DecisionModel (using its exact target_entity_id and target_entity_type).
   Valid entity types: 'assumption', 'unknown', 'variable', 'constraint', 'tradeoff', 'objective'.
2. Classify the inquiry into exactly ONE EvidenceKind:
   - EXTERNAL_RESEARCH: Public benchmarks, industry reports, academic literature, competitor data, or external market studies.
     May provide 1-3 concise, neutral, factual search queries.
     Do NOT write leading or confirmation-bias queries.
   - INTERNAL_DATA: Private, organization-specific metrics or historical records (e.g. internal CAC, current churn, internal margins, conversion rates, customer counts).
     MUST NOT provide search queries.
   - USER_CLARIFICATION: Subjective preferences, strategic risk tolerance, definitions, or intentions of the decision-maker.
     MUST NOT provide search queries.
   - DETERMINISTIC_CALCULATION: Mathematical transformations or arithmetic relationships (e.g. break-even volume increase, margin threshold math).
     Do NOT perform the calculation. MUST NOT provide search queries.
3. Provenance Rule:
   - Do NOT create requirements to verify facts already provided by the user (e.g., if the user stated a 20% discount or a specific constraint, do not create a requirement asking to verify that the value is 20%).
4. Do NOT make recommendations or propose a final decision.
"""


def build_requirements_prompt(model: DecisionModel) -> str:
    """Constructs prompt for evidence requirement extraction from DecisionModel."""
    sections: List[str] = [
        f"Decision Problem:\n{model.decision.summary}",
        "Primary Objective:\n" + "\n".join(f"- {o.id}: {o.description}" for o in model.objectives if o.is_primary),
    ]

    if model.assumptions:
        sections.append("Assumptions Needing Falsification/Validation:\n" + "\n".join(
            f"- {a.id} ({a.confidence.value}): {a.statement}" for a in model.assumptions
        ))

    if model.unknowns:
        sections.append("Identified Empirical Unknowns:\n" + "\n".join(
            f"- {u.id} (priority: {u.criticality.value}): {u.question}" for u in model.unknowns
        ))

    unresolved_vars = [v for v in model.variables if v.baseline_value is None or v.proposed_value is None]
    if unresolved_vars:
        sections.append("Unresolved / Inferred Variables:\n" + "\n".join(
            f"- {v.id}: {v.name} - {v.description} (baseline: {v.baseline_value or 'unknown'}, proposed: {v.proposed_value or 'unknown'}, provenance: {v.provenance.value})"
            for v in unresolved_vars
        ))

    user_vars = [v for v in model.variables if v.proposed_provenance == ProvenanceType.USER_PROVIDED and v.proposed_value is not None]
    if user_vars:
        sections.append("User-Provided Facts (DO NOT generate requirements to verify these values):\n" + "\n".join(
            f"- {v.id}: {v.name} = {v.proposed_value} {v.unit or ''} (user provided)"
            for v in user_vars
        ))

    if model.constraints:
        sections.append("Constraints:\n" + "\n".join(
            f"- {c.id}: {c.name} - {c.description} (source: {c.source}, hard: {c.is_hard_constraint})"
            for c in model.constraints
        ))

    sections.append("Analyze the decision entities above and output the candidate evidence requirements.")
    return "\n\n".join(sections)


# ------------------------------------------------------------------------------
# 3. Target Reference Validation Helpers
# ------------------------------------------------------------------------------

def _build_entity_map(model: DecisionModel) -> Dict[str, DecisionEntityType]:
    """Builds a lookup mapping entity ID to DecisionEntityType for a DecisionModel."""
    mapping: Dict[str, DecisionEntityType] = {}
    for o in model.objectives:
        mapping[o.id] = DecisionEntityType.OBJECTIVE
    for v in model.variables:
        mapping[v.id] = DecisionEntityType.VARIABLE
    for c in model.constraints:
        mapping[c.id] = DecisionEntityType.CONSTRAINT
    for s in model.stakeholders:
        mapping[s.id] = DecisionEntityType.STAKEHOLDER
    for t in model.tradeoffs:
        mapping[t.id] = DecisionEntityType.TRADEOFF
    for a in model.assumptions:
        mapping[a.id] = DecisionEntityType.ASSUMPTION
    for u in model.unknowns:
        mapping[u.id] = DecisionEntityType.UNKNOWN
    mapping[model.id] = DecisionEntityType.DECISION
    return mapping


def validate_target_reference(
    decision_model: DecisionModel,
    target_id: str,
    target_type: DecisionEntityType,
) -> None:
    """Validates that target_id exists in decision_model and matches target_type.

    Raises:
        ValueError: If target_id is not found or target_type does not match the actual entity type.
    """
    entity_map = _build_entity_map(decision_model)
    if target_id not in entity_map:
        raise ValueError(
            f"Target entity '{target_id}' of type '{target_type.value}' does not exist in DecisionModel '{decision_model.id}'."
        )
    actual_type = entity_map[target_id]
    if target_type != actual_type:
        raise ValueError(
            f"Mismatched target_entity_type for entity '{target_id}': expected '{actual_type.value}', got '{target_type.value}'."
        )


def _is_verifying_user_provided_fact(
    candidate: CandidateEvidenceRequirement,
    model: DecisionModel,
) -> bool:
    """Returns True if candidate is redundantly attempting to prove an established user fact."""
    desc_lower = candidate.description.lower()

    if candidate.target_entity_type == DecisionEntityType.VARIABLE:
        var = next((v for v in model.variables if v.id == candidate.target_entity_id), None)
        if var and var.proposed_provenance == ProvenanceType.USER_PROVIDED and var.proposed_value is not None:
            val_str = str(var.proposed_value).rstrip(".0") if isinstance(var.proposed_value, float) and var.proposed_value.is_integer() else str(var.proposed_value)
            verifying_patterns = [
                f"verify that the proposed value is {val_str}",
                f"verify whether the user proposed a {val_str}",
                f"verify whether the user proposed {val_str}",
                f"verify if the user proposed {val_str}",
                f"verify that the value is {val_str}",
                f"verify that pricing is reduced by {val_str}",
                f"verify that the discount is {val_str}",
                f"verify that the proposed reduction is {val_str}",
                f"prove that the proposed value is {val_str}",
                f"confirm the user wants to reduce by {val_str}",
                f"verify that our startup plans to reduce pricing by {val_str}",
            ]
            if any(p in desc_lower for p in verifying_patterns):
                return True

    elif candidate.target_entity_type == DecisionEntityType.CONSTRAINT:
        cnstr = next((c for c in model.constraints if c.id == candidate.target_entity_id), None)
        if cnstr and cnstr.provenance == ProvenanceType.USER_PROVIDED:
            if any(p in desc_lower for p in ["verify that the user stated", "confirm user constraint", "verify user constraint"]):
                return True

    return False


def _audit_and_reconcile_requirement_kind(
    kind: EvidenceKind,
    description: str,
) -> EvidenceKind:
    """Detects and repairs semantic contradictions between kind and description.

    Guarantees:
    - EXTERNAL_RESEARCH asking for private internal metrics is repaired to INTERNAL_DATA.
    - INTERNAL_DATA asking for public industry benchmarks is repaired to EXTERNAL_RESEARCH.
    - USER_CLARIFICATION asking for published studies is repaired to EXTERNAL_RESEARCH.
    """
    desc_lower = description.lower()

    # Signals indicating private corporate records/data
    internal_signals = [
        "our company's", "our internal", "private current", "internal proprietary",
        "internal records", "our confidential", "internal database", "private internal",
        "internal cac", "internal churn", "internal cost", "our books", "internal data",
    ]
    # Signals indicating public external research/benchmarks
    external_signals = [
        "public saas benchmark", "industry reports", "published studies",
        "academic literature", "market research study", "public benchmark",
        "industry benchmark", "competitor filings", "published research",
        "search published", "external benchmark", "public reports",
    ]

    # Rule 1: EXTERNAL_RESEARCH asking for private internal data -> repair to INTERNAL_DATA
    if kind == EvidenceKind.EXTERNAL_RESEARCH and any(s in desc_lower for s in internal_signals):
        return EvidenceKind.INTERNAL_DATA

    # Rule 2: INTERNAL_DATA asking for public external research -> repair to EXTERNAL_RESEARCH
    if kind == EvidenceKind.INTERNAL_DATA and any(s in desc_lower for s in external_signals):
        return EvidenceKind.EXTERNAL_RESEARCH

    # Rule 3: USER_CLARIFICATION asking for public external research -> repair to EXTERNAL_RESEARCH
    if kind == EvidenceKind.USER_CLARIFICATION and any(s in desc_lower for s in external_signals):
        return EvidenceKind.EXTERNAL_RESEARCH

    return kind


# ------------------------------------------------------------------------------
# 4. Canonical Default Generator (for FakeLLMClient / Mock Fallbacks)
# ------------------------------------------------------------------------------

def get_default_candidate_requirements(model: Optional[DecisionModel] = None) -> CandidateRequirementsPayload:
    """Generates realistic default candidate requirements for offline testing."""
    return CandidateRequirementsPayload(
        requirements=[
            CandidateEvidenceRequirement(
                target_entity_id="asm_elasticity",
                target_entity_type=DecisionEntityType.ASSUMPTION,
                kind=EvidenceKind.EXTERNAL_RESEARCH,
                description="Empirical price elasticity benchmarks for B2B SaaS price reductions.",
                priority=CriticalityLevel.HIGH,
                suggested_queries=[
                    "B2B SaaS price elasticity customer acquisition",
                    "SaaS discount conversion rate benchmark",
                ],
            ),
            CandidateEvidenceRequirement(
                target_entity_id="var_monthly_churn",
                target_entity_type=DecisionEntityType.VARIABLE,
                kind=EvidenceKind.INTERNAL_DATA,
                description="Historical internal monthly churn rate prior to price discount.",
                priority=CriticalityLevel.HIGH,
                suggested_queries=[],
            ),
            CandidateEvidenceRequirement(
                target_entity_id="unk_competitor_pricing",
                target_entity_type=DecisionEntityType.UNKNOWN,
                kind=EvidenceKind.EXTERNAL_RESEARCH,
                description="Competitor pricing intelligence and discount matching patterns.",
                priority=CriticalityLevel.MEDIUM,
                suggested_queries=[
                    "SaaS competitor price matching response patterns",
                ],
            ),
            CandidateEvidenceRequirement(
                target_entity_id="stk_prospects",
                target_entity_type=DecisionEntityType.STAKEHOLDER,
                kind=EvidenceKind.USER_CLARIFICATION,
                description="Target prospect price sensitivity definition and tier boundaries.",
                priority=CriticalityLevel.MEDIUM,
                suggested_queries=[],
            ),
            CandidateEvidenceRequirement(
                target_entity_id="trd_volume_vs_arpu",
                target_entity_type=DecisionEntityType.TRADEOFF,
                kind=EvidenceKind.DETERMINISTIC_CALCULATION,
                description="Calculate break-even sales volume increase required to offset 20% ARPU decline.",
                priority=CriticalityLevel.HIGH,
                suggested_queries=[],
            ),
        ]
    )


# ------------------------------------------------------------------------------
# 5. EvidenceRequirementEngine Implementation
# ------------------------------------------------------------------------------

class EvidenceRequirementEngine:
    """Identifies, classifies, and policy-audits empirical evidence requirements from a DecisionModel."""

    def __init__(self, llm_client: LLMClient) -> None:
        """Initializes EvidenceRequirementEngine.

        Args:
            llm_client: Injected LLMClient instance (e.g. FakeLLMClient in tests).
        """
        self.llm_client = llm_client

    def generate_requirements(
        self,
        decision_model: DecisionModel,
        deadline_monotonic: Optional[float] = None,
    ) -> List[EvidenceRequirement]:
        """Analyzes a DecisionModel and produces a deduplicated, validated list of EvidenceRequirement.

        Args:
            decision_model: The canonical DecisionModel to evaluate.
            deadline_monotonic: Optional absolute monotonic deadline for the operation.

        Returns:
            List[EvidenceRequirement] with status=PENDING and strictly enforced query policies.

        Raises:
            ValueError: If target entities are invalid or mismatched.
            LLMError: If upstream LLM generation fails.
        """
        if deadline_monotonic is not None and time.monotonic() >= deadline_monotonic:
            raise LLMTimeoutError("Operation timed out before evidence requirements generation could begin.")

        # 1. Build prompt
        prompt = build_requirements_prompt(decision_model)

        # 2. Invoke structured generation
        try:
            candidate_payload = self.llm_client.generate_structured(
                prompt=prompt,
                response_schema=CandidateRequirementsPayload,
                system_instruction=REQUIREMENTS_SYSTEM_PROMPT,
                deadline_monotonic=deadline_monotonic,
            )
        except TypeError as te:
            if "unexpected keyword argument 'deadline_monotonic'" in str(te):
                candidate_payload = self.llm_client.generate_structured(
                    prompt=prompt,
                    response_schema=CandidateRequirementsPayload,
                    system_instruction=REQUIREMENTS_SYSTEM_PROMPT,
                )
            else:
                raise

        # 3. Policy enforcement, reference validation, and deduplication
        requirements: List[EvidenceRequirement] = []
        seen_targets: Set[tuple[str, EvidenceKind]] = set()
        req_counter = 1

        for candidate in candidate_payload.requirements:
            # Enforce target validation (raises ValueError on invalid reference)
            validate_target_reference(
                decision_model=decision_model,
                target_id=candidate.target_entity_id,
                target_type=candidate.target_entity_type,
            )

            # Enforce user-provided fact guard
            if _is_verifying_user_provided_fact(candidate, decision_model):
                continue

            # Audit and reconcile requirement kind against semantic contradictions
            reconciled_kind = _audit_and_reconcile_requirement_kind(
                kind=candidate.kind,
                description=candidate.description,
            )

            # Enforce deduplication (preserves distinct requirements for same target)
            norm_desc = " ".join(candidate.description.strip().lower().split())
            target_key = (candidate.target_entity_id, reconciled_kind, norm_desc)
            if target_key in seen_targets:
                continue
            seen_targets.add(target_key)

            # Enforce query policy based on reconciled EvidenceKind
            if reconciled_kind == EvidenceKind.EXTERNAL_RESEARCH:
                # Retain clean, non-empty search queries up to max 5
                queries = [q.strip() for q in candidate.suggested_queries if q and q.strip()][:5]
                if not queries:
                    clean_desc_query = " ".join(candidate.description.strip().split())[:100]
                    queries = [clean_desc_query]
            else:
                # Deterministic policy: suggested_queries MUST be [] for internal, user, or math
                queries = []

            # Construct canonical EvidenceRequirement
            req_id = f"req_{req_counter}"
            req_counter += 1

            req = EvidenceRequirement(
                id=req_id,
                target_entity_id=candidate.target_entity_id,
                target_entity_type=candidate.target_entity_type,
                kind=reconciled_kind,
                description=candidate.description.strip(),
                priority=candidate.priority,
                status=RequirementStatus.PENDING,  # Strictly initialized to PENDING
                suggested_queries=queries,
            )
            requirements.append(req)

        return requirements
